// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic structure
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          pan_card: string | null;
          kyc_status: string;
          balance_inr: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      watchlist: {
        Row: {
          id: string;
          user_id: string;
          coin_id: string;
          coin_symbol: string;
          added_at: string;
        };
        Insert: Omit<Database['public']['Tables']['watchlist']['Row'], 'id' | 'added_at'>;
        Update: Partial<Database['public']['Tables']['watchlist']['Insert']>;
      };
      orders: {
        Row: {
          id: string;
          user_id: string;
          coin_id: string;
          coin_symbol: string;
          order_type: string;
          order_mode: string;
          order_status: string;
          quantity: number;
          price_per_unit: number | null;
          total_amount: number;
          order_date: string;
          completed_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['orders']['Row'], 'id' | 'order_date'>;
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
      };
      transactions: {
        Row: {
          id: string;
          user_id: string;
          order_id: string;
          transaction_type: string;
          coin_id: string;
          coin_symbol: string;
          quantity: number;
          price_per_unit: number;
          total_amount: number;
          transaction_date: string;
        };
        Insert: Omit<Database['public']['Tables']['transactions']['Row'], 'id' | 'transaction_date'>;
        Update: Partial<Database['public']['Tables']['transactions']['Insert']>;
      };
      holdings: {
        Row: {
          id: string;
          user_id: string;
          coin_id: string;
          coin_symbol: string;
          quantity: number;
          average_buy_price: number;
          last_updated: string;
        };
        Insert: Omit<Database['public']['Tables']['holdings']['Row'], 'id' | 'last_updated'>;
        Update: Partial<Database['public']['Tables']['holdings']['Insert']>;
      };
      automation_scripts: {
        Row: {
          id: string;
          user_id: string;
          script_name: string;
          script_code: string;
          script_type: string;
          is_active: boolean;
          config: Record<string, any>;
          created_at: string;
          updated_at: string;
          last_executed_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['automation_scripts']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['automation_scripts']['Insert']>;
      };
      script_executions: {
        Row: {
          id: string;
          script_id: string;
          user_id: string;
          execution_status: string;
          orders_placed: number;
          error_message: string | null;
          execution_log: Record<string, any>;
          started_at: string;
          completed_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['script_executions']['Row'], 'id' | 'started_at'>;
        Update: Partial<Database['public']['Tables']['script_executions']['Insert']>;
      };
    };
  };
};

